// This file was autogenerated by closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/sophilabs/ui/rule.js', ['sophilabs.ui.Rule'], ['goog.dom', 'goog.dom.classes']);
