// This file was autogenerated by closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/sophilabs/ui/rangeslider.js', ['sophilabs.ui.RangeSlider'], ['goog.dom', 'goog.dom.a11y', 'goog.dom.a11y.Role', 'goog.ui.SliderBase']);
goog.addDependency('../../src/sophilabs/ui/rule.js', ['sophilabs.ui.Rule'], ['goog.dom', 'goog.dom.classes']);
